/* Botning barcha gaplari — uch tilda. */
const T = {
uz: {
  chooseLang: "Tilni tanlang / Выберите язык / Choose a language",
  welcome: "Salom! Men rezyume yasayman va tayyor PDF qilib yuboraman.\n\nIkki yo'l bor:\n• Savollarga javob berasiz — men so'rab boraman\n• Yoki «Tahrirlash» tugmasi bilan qulay oynada to'ldirasiz\n\nIkkinchi yo'lni tanlasangiz — pastdagi «Tahrirlash» tugmasini bosing.\n\nBirinchi yo'l bilan boshlaymiz. Ism-familiyangizni yozing:",
  askName: "Ism-familiyangizni yozing:",
  askRole: "Kasbingiz yoki lavozimingiz? (masalan: Marketing menejeri)",
  askContact: "Aloqa ma'lumotlari. BITTA xabarda, har biri alohida qatorda:\n\n1) telefon\n2) email\n3) shahar\n4) havola (linkedin, sayt)\n\nBo'lmaganiga chiziqcha ( - ) qo'ying.\n\nMasalan:\n+998 90 123 45 67\nali@mail.com\nToshkent\n-",
  askPhoto: "Foto yuboring (ixtiyoriy). Kerak bo'lmasa «O'tkazib yuborish» tugmasini bosing.",
  askSummary: "O'zingiz haqingizda 2-3 gap yozing. Nima ish qilasiz, nimada kuchlisiz?",
  askExp: "Endi ish tajribangiz. Bitta ish joyini BITTA xabarda yuboring:\n\n1-qator: lavozim\n2-qator: tashkilot\n3-qator: muddat\n4-qatordan boshlab: vazifalaringiz\n\nMasalan:\nMarketing menejeri\nAlfa Digital\n2022 — hozir\nReklama byudjetini boshqarganman\n4 kishilik jamoaga rahbarlik qilganman",
  addedExp: "Qo'shildi ✅ Yana ish joyi bormi?",
  askEdu: "Ta'limingiz. Bitta o'quv joyini BITTA xabarda:\n\n1-qator: yo'nalish yoki daraja\n2-qator: o'quv muassasasi\n3-qator: yillar\n\nMasalan:\nMarketing, bakalavr\nTDIU\n2015 — 2019",
  addedEdu: "Qo'shildi ✅ Yana ta'lim bormi?",
  askSkills: "Ko'nikmalaringiz — har biri alohida qatorda.\n\nDaraja chizig'i kerak bo'lsa, oxiriga | va raqam qo'ying:\n\nExcel | 85\nGoogle Ads | 70\nJamoa boshqaruvi",
  askLangs: "Bilgan tillaringiz — har biri alohida qatorda, «til — daraja» ko'rinishida:\n\nO'zbek — ona tili\nRus — C1\nIngliz — B2",
  askCerts: "Sertifikatlaringiz — har biri alohida qatorda, «nomi — beruvchi — yil»:\n\nGoogle Ads — Google — 2023\n\nBo'lmasa «O'tkazib yuborish»ni bosing.",
  chooseTpl: "Ma'lumot tayyor! Endi ko'rinishini tanlang. Bosishingiz bilan PDF yasayman.",
  making: "PDF yasayapman… 10-20 soniya kuting ⏳",
  caption: "Rezyumengiz tayyor ✅\n\nBoshqa ko'rinishni sinab ko'rish yoki matnni tahrirlash uchun quyidagi tugmalardan foydalaning.",
  err: "Kechirasiz, PDF yasashda xatolik bo'ldi. Yana urinib ko'ring: /pdf",
  noData: "Avval ma'lumot kiritishimiz kerak. /start bosing.",
  resetOk: "Hammasi tozalandi. /start bosing.",
  help: "Buyruqlar:\n/start — boshidan boshlash\n/app — qulay oynada tahrirlash\n/pdf — PDF'ni qayta yuborish\n/tpl — ko'rinishni almashtirish\n/reset — hammasini o'chirish",
  waking: "Bir soniya, uyg'onyapman…",
  btnSkip: "O'tkazib yuborish",
  btnMore: "Yana qo'shish",
  btnNext: "Keyingisi ▶",
  btnApp: "✏️ Tahrirlash (qulay oyna)",
  btnTpl: "🎨 Boshqa ko'rinish",
  btnPdf: "📄 PDF olish",
  savedFromApp: "Tahrirlash oynasidan qabul qilindi ✅"
},
ru: {
  chooseLang: "Tilni tanlang / Выберите язык / Choose a language",
  welcome: "Привет! Я сделаю резюме и пришлю готовый PDF.\n\nДва способа:\n• Ответить на мои вопросы\n• Или заполнить в удобном окне через кнопку «Редактировать»\n\nВторой способ — нажмите кнопку «Редактировать» ниже.\n\nИначе начнём с вопросов. Напишите имя и фамилию:",
  askName: "Напишите имя и фамилию:",
  askRole: "Ваша профессия или должность? (например: Менеджер по маркетингу)",
  askContact: "Контакты. ОДНИМ сообщением, каждый с новой строки:\n\n1) телефон\n2) email\n3) город\n4) ссылка\n\nЕсли чего-то нет — поставьте дефис ( - ).",
  askPhoto: "Пришлите фото (по желанию). Не нужно — нажмите «Пропустить».",
  askSummary: "Напишите 2-3 предложения о себе: чем занимаетесь, в чём сильны?",
  askExp: "Опыт работы. Одно место — ОДНИМ сообщением:\n\n1 строка: должность\n2 строка: организация\n3 строка: период\nдалее: обязанности",
  addedExp: "Добавлено ✅ Есть ещё место работы?",
  askEdu: "Образование. Одно место — ОДНИМ сообщением:\n\n1 строка: направление или степень\n2 строка: учебное заведение\n3 строка: годы",
  addedEdu: "Добавлено ✅ Есть ещё образование?",
  askSkills: "Навыки — каждый с новой строки.\n\nДля шкалы уровня добавьте | и число:\n\nExcel | 85\nGoogle Ads | 70",
  askLangs: "Языки — каждый с новой строки, «язык — уровень»:\n\nРусский — родной\nАнглийский — B2",
  askCerts: "Сертификаты — каждый с новой строки, «название — кем выдан — год».\n\nНет — нажмите «Пропустить».",
  chooseTpl: "Данные готовы! Выберите оформление — сразу сделаю PDF.",
  making: "Делаю PDF… подождите 10-20 секунд ⏳",
  caption: "Ваше резюме готово ✅",
  err: "Не получилось сделать PDF. Попробуйте ещё раз: /pdf",
  noData: "Сначала нужно ввести данные. Нажмите /start",
  resetOk: "Всё очищено. Нажмите /start",
  help: "Команды:\n/start — начать заново\n/app — редактировать в окне\n/pdf — прислать PDF снова\n/tpl — сменить оформление\n/reset — удалить всё",
  waking: "Секунду, просыпаюсь…",
  btnSkip: "Пропустить",
  btnMore: "Добавить ещё",
  btnNext: "Далее ▶",
  btnApp: "✏️ Редактировать",
  btnTpl: "🎨 Другое оформление",
  btnPdf: "📄 Получить PDF",
  savedFromApp: "Принято из окна редактирования ✅"
},
en: {
  chooseLang: "Tilni tanlang / Выберите язык / Choose a language",
  welcome: "Hi! I build resumes and send you a ready PDF.\n\nTwo ways:\n• Answer my questions\n• Or fill everything in a comfortable window via «Edit»\n\nFor the second way — press «Edit» below.\n\nOtherwise let's start. Type your full name:",
  askName: "Type your full name:",
  askRole: "Your profession or job title? (e.g. Marketing Manager)",
  askContact: "Contact details. In ONE message, each on its own line:\n\n1) phone\n2) email\n3) city\n4) link\n\nUse a dash ( - ) for anything you don't have.",
  askPhoto: "Send a photo (optional). Not needed — press «Skip».",
  askSummary: "Write 2-3 sentences about yourself: what you do, what you're good at.",
  askExp: "Work experience. One job per message:\n\nline 1: position\nline 2: organisation\nline 3: period\nthen: your responsibilities",
  addedExp: "Added ✅ Another job?",
  askEdu: "Education. One entry per message:\n\nline 1: field or degree\nline 2: institution\nline 3: years",
  addedEdu: "Added ✅ More education?",
  askSkills: "Skills — one per line.\n\nFor a level bar add | and a number:\n\nExcel | 85\nGoogle Ads | 70",
  askLangs: "Languages — one per line, «language — level»:\n\nEnglish — native\nRussian — B2",
  askCerts: "Certificates — one per line, «title — issuer — year».\n\nNone — press «Skip».",
  chooseTpl: "Data is ready! Pick a look — I'll build the PDF right away.",
  making: "Building the PDF… 10-20 seconds ⏳",
  caption: "Your resume is ready ✅",
  err: "PDF failed. Please try again: /pdf",
  noData: "We need your details first. Press /start",
  resetOk: "Everything cleared. Press /start",
  help: "Commands:\n/start — start over\n/app — edit in a window\n/pdf — send the PDF again\n/tpl — change the look\n/reset — delete everything",
  waking: "One moment, waking up…",
  btnSkip: "Skip",
  btnMore: "Add another",
  btnNext: "Next ▶",
  btnApp: "✏️ Edit in window",
  btnTpl: "🎨 Another look",
  btnPdf: "📄 Get PDF",
  savedFromApp: "Received from the editor ✅"
}
};
module.exports = (lang) => T[lang] || T.uz;
